name: flutterperu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/incas.jpg
   - assets/Peru.jpg
   - assets/iconsinca.png
   - assets/historia1.webp
   - assets/mapa-peru.webp
   - assets/perga.jpg
   - assets/pe.jpg
   - assets/p.jpg
   - assets/perg.jpg
   - assets/historia2.jpg
   - assets/HISTORIA3.png
   - assets/cul.png
   - assets/comid.png
   - assets/in.png
   - assets/Lhama.jpg
   - assets/lha.png
   - assets/c.png
  